version: 2

sources:
  - name: staging
    # This tells dbt to look in your specific dataset
    schema: nytaxi
    tables:
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_green_tripdata
    description: "Staging model for Green Taxi data"
    columns:
      - name: tripid
        tests:
          - unique
          - not_null

  - name: stg_yellow_tripdata
    description: "Staging model for Yellow Taxi data"
    columns:
      - name: tripid
        tests:
          - unique
          - not_null